### ISSUE TITLE
`std::any` requires no calls to new?

### ISSUE THREAD

**Issue by theres-waldo** [tvaneerd/cpp17_in_TTs#13]
The Tony Table for `std::any` says that `any` it does not require calls to `new`.

I think that's a bit misleading. The object still needs to be stored somewhere, and the only way to avoid storing it on the heap is to use a small-object optimization, which only applies to objects that are sufficiently small (in the libcxx implementation, 3 words in size or smaller).

**Comment by tvaneerd** [comment]
Agreed.
Will fix.
