### ISSUE TITLE
Mistake in first table in structured_bindings.md?

### ISSUE THREAD

**Issue by jurajplavcan** [tvaneerd/cpp17_in_TTs#9]
Hi
I'm not sure if you didn't mean **C++11** in the first column of the table. Well, it's right to put C++14, as it should be valid C++14, but I was just wondering.
I hope I'm not wasting your time with this. I'm just learning :)
Thanks,
Juraj

**Comment by tvaneerd** [comment]
I've updated it to hopefully be more clear - I've extended the C++14 header across the first two columns.
The idea is that the first two columns are the 2 common ways to handle it in C++14, and C++17 structured bindings can replace both.
